### ISSUE TITLE
Autocomplete is hidden behind current tiddler.

### ISSUE THREAD

**Issue by ssoriche** [Gk0Wk/TW5-CodeMirror-Enhanced#30]
Hi, I recently migrated from CodeMirror-Mode-TiddlyWiki5 and have run into the problem again where the autocomplete window is always behind the tiddler and I'm unable to see/use the autocomplete.

I had a look and the zindex is set to 800, where this commit changed it to a really big number in the old repository.

https://github.com/Gk0Wk/CodeMirror-Mode-TiddlyWiki5/commit/96f3aea23a53fdb28883c0c515bf9278352b2604

I tried manually updating my installation but it hasn't had an effect.

**Comment by cdaven** [comment]
It looks like the whole CSS file is ignored in this build, but you can fix it in your own TiddlyWiki.

Edit `$:/plugins/Gk0Wk/TW5-CodeMirror-Enhanced/style.css` and insert two newlines after the first line, so that it looks like this:

```
\rules only filteredtranscludeinline transcludeinline macrodef macrocallinline html

.CodeMirror-hints{z-index:800!important;background:<<colour background>>!important;border:1px solid <<colour table-border>>!important; ...
```

To whoever may or may not be maintaining this plugin (@linonetwo?), have a look at the minification of the CSS in build.py or somewhere.

**Comment by linonetwo** [comment]
I will take time to review PR, but I'm working on [https://github.com/tiddly-gittly/Awesome-TiddlyWiki-Editions](https://github.com/tiddly-gittly/Awesome-TiddlyWiki-Editions) recently.

**Comment by linonetwo** [comment]
Already fixed in latest version
